Fix apt-get upgrade
RevolutionPi/revpi-tools pull request #24
Opened 2023-01-10 17:44 UTC by iluminat23

2023-01-10 17:58 UTC, nbuchwitz requested changes
Commit msg: behavoir - > behavior

2023-01-10 18:11 UTC, nbuchwitz approved these changes

2023-01-10 19:55 UTC, l1k commented
How about just splitting out revpi-sos-report into a separate package?

2023-01-10 20:43 UTC, nbuchwitz commented
@l1k this on the agenda for bullseye. In this particular case this won't solve the problem as the problem is caused by an additional package in our dependencies. If we would split SOS report into a separate package without an upgrade path via dependencies this would result in systems without installed sos report. So for now moving the additional package from a dependency to a suggestion is our best shot (transition from Buster to bullseye where we can change and split thing will require a dist upgrade, so we will be change this back to a requirement then)

2023-01-11 11:22 UTC, naruxde approved these changes

2023-01-11 13:03 UTC, merged