Fix license copyright
RevolutionPi/revpi-tools pull request #26
Opened 2023-03-07 14:54 UTC by RamiGspo

Fix license copyright for Kunbus

2023-03-07 14:58 UTC, nbuchwitz requested changes

2023-03-07 14:58 UTC, nbuchwitz commented on LICENSES/MIT.txt
> +Copyright (c) 2021-2023 KUNBUS-GmbH
```suggestion
Copyright (c) 2021-2023 KUNBUS GmbH
```

2023-03-07 15:20 UTC, RamiGspo commented on LICENSES/MIT.txt
> +Copyright (c) 2021-2023 KUNBUS-GmbH
Thank you!

2023-03-07 15:22 UTC, naruxde approved these changes

2023-03-07 20:56 UTC, nbuchwitz approved these changes

2023-03-08 07:16 UTC, iluminat23 approved these changes

2023-03-08 09:15 UTC, merged