Feature/revpi 2832/rev pi autodiscovery
RevolutionPi/revpi-tools pull request #27
Opened 2023-03-09 13:21 UTC by maosswald

2023-03-09 13:36 UTC, naruxde requested changes
Your avahi service is no systemd-unit file, so wrong directory to place in revpi-tools.
Did you think about the file name `revpi.service`? We want to announce SSH with avahi.

Did you check the [avahi-daemon](https://packages.debian.org/buster/avahi-daemon) package? Maybe they offer examples for default services like ssh?

2023-03-10 13:07 UTC, naruxde requested changes
Your commit message should use other head text und needs a message. What will this commit do.

2023-03-10 13:07 UTC, naruxde commented on systemd/CMakeLists.txt
> +
```suggestion
```

2023-03-10 13:07 UTC, naruxde commented on systemd/CMakeLists.txt
> +
Just drop changes in this file, because you do not have to touch it for this commit.

2023-03-10 13:07 UTC, naruxde commented on CMakeLists.txt
> +add_subdirectory(avahi-service)
```suggestion
add_subdirectory(avahi-services)
```

I would add an 's' so you reference the meaning to /etc/avahi/services folder. Maybe we add more files here in the future.

2023-03-10 13:07 UTC, naruxde commented on avahi-service/revpi.service
> +<?xml version="1.0" standalone='no'?>
Yesterday you told us, you would NOT use the name `revpi.service`. I would suggest to rename the file to `revpi-ssh.service`. The prefix could be important and indicates that it is our file.

Other files form web status could be `revpi-http.service` or things like that.

2023-03-13 09:43 UTC, closed without merging

2023-03-13 10:14 UTC, RamiGspo commented
Why closed?

2023-03-13 10:17 UTC, maosswald commented
Because it was only a test to learn git look at jira ticket theres a better solution than a pull request

2023-03-14 08:54 UTC, RamiGspo commented
@maosswald 
Maybe I am missing something, because I did not find any Information in your Jira Ticket...

2023-03-20 23:56 UTC, RamiGspo commented
@maosswald I used your files to continue with your Ticket.
The new PR ist here: [PR#30](https://github.com/RevolutionPi/revpi-tools/pull/30)
Maybe you want to do the other part for WebStatus...